### ISSUE TITLE
Create a batch effect section

### ISSUE THREAD

**Issue by kcotto** [griffithlab/rnabio.org#19]
Migrated from rnabio.org proposed improvements page

We should add a section about batch effects. Both detecting the presence of batch effects as well as correcting for them during analysis.

Use the Snyder lab mouse/human tissue expression data as an example?

**Comment by malachig** [comment]
Based on COMBAT perhaps?

**Comment by malachig** [comment]
https://pubmed.ncbi.nlm.nih.gov/33015620/
ComBat-seq: batch effect adjustment for RNA-seq count data

**Comment by malachig** [comment]
https://rdrr.io/bioc/sva/man/ComBat_seq.html

**Comment by malachig** [comment]
One idea for data to demonstrate batch analysis could be obtained from this study which has deposited data in GEO:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4167418/
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE46876

They performed sequencing of UHR and HBR samples (with ERCC spike-in's) just as we did for this course.  They also compared the impact of RNA degradation and enrichment strategy (ribo depletion vs polyA selection): "results from ribosomal RNA-depleted and polyA-enriched libraries from intact RNA were compared using the Illumina HiSeq 2500 platform.".

So for example, we could perform DE analysis of UHR vs HBR where we consider the batch effect of Ribo-depleted (RD) and polyA-enriched  (PE) samples. 

We could evaluate batch correction in several ways.  e.g. we could do PCA or MDS analysis of expression profiles for:
- 3 replicates of UHR Ribo-depleted
- 3 replicates of HBR Ribo-depleted
- 3 replicates of UHR PolyA-enriched
- 3 replicates of HBR PolyA-enriched

Is the clustering driven by the biology of the sample (UHR vs HBR)? Or the sample prep approach?  Does batch correction help?

Similarly, you could perform DE analysis of:
- UHR Ribo-depleted vs HBR Ribo-depleted
- UHR PolyA-enriched vs HBR PolyA-enriched
- UHR Ribo-depleted vs HBR PolyA-enriched
- UHR PolyA-enriched vs HBR UHR Ribo-depleted

How much impact does it have to compare Ribo-depleted data to PolyA-enriched?  If you do batch correction and redo these comparisons does it make the results more comparable?  i.e. can we correct for the technical differences and see the same biological differences?

This is a bit contrived because there really are true biological differences expected for polyA vs. Ribo-depleted data.  To counter this, we could limit the analysis to only know protein coding genes.

There are other experiments from this dataset we could use instead.  For example, different levels of degradation?, data generated by different labs?  [Figure 1](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4167418/) and [Figure 2](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4167418/) give a nice high level summary of all the data generated.

**Comment by kcotto** [comment]
File containing sample info for GEO
[GSE46876_family.soft.gz](https://github.com/griffithlab/rnabio.org/files/5563095/GSE46876_family.soft.gz)

GSE48035_series_matrix.txt.gz
ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE48nnn/GSE48035/matrix/GSE48035_series_matrix.txt.gz

**Comment by malachig** [comment]
A slightly more detailed demonstration of COMBAT-Seq: https://github.com/zhangyuqing/ComBat-seq

**Comment by malachig** [comment]
It looks like we could download pre-computed raw counts for the Illumina subset of data from the above publication here (PMC4167418): [GSE48035_ILMN.counts.txt.gz](https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE48035&format=file&file=GSE48035%5FILMN%2Ecounts%2Etxt%2Egz)

Data processing is described as:
STAR Aligner v2.3.0 Long Read counts were calculated using the Rmake pipeline (http://physiology.med.cornell.edu/faculty/mason/lab/r-make/) with Gencode v12 annotation. Genome_build: hg19.

In GEO, these data are organized as a `superseries`: [GSE46876](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE46876) which has data for several sequencing platforms.  The data from the Illumina Platform are part of this subseries: [GSE48035](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE48035). 

Samples we could use for this analysis:

ABRF-ILMN-RIBO-A-1
ABRF-ILMN-RIBO-A-2
ABRF-ILMN-RIBO-A-3
ABRF-ILMN-RIBO-A-4

ABRF-ILMN-RIBO-B-1
ABRF-ILMN-RIBO-B-2
ABRF-ILMN-RIBO-B-3
ABRF-ILMN-RIBO-B-4

ABRF-ILMN-RNA-A-1
ABRF-ILMN-RNA-A-2
ABRF-ILMN-RNA-A-3
ABRF-ILMN-RNA-A-4

ABRF-ILMN-RNA-B-1
ABRF-ILMN-RNA-B-2
ABRF-ILMN-RNA-B-3
ABRF-ILMN-RNA-B-4

Where:
- Two standard RNA samples (`A` = Universal Human Reference RNA and `B` = Human Brain Reference RNA) were combined with two sets of synthetic RNAs (ERCCs).
- `ILMN` = Illumina platform
- `RNA` = polyA enrichment and `RIBO` = ribosomal RNA depletion
- `1`, `2`, `3`, `4` are technical replicates

**Comment by malachig** [comment]
This section has now been completed and tested.
